package com.trapezoidlimited.groundforce.utils

const val SHARED_PREFS: String = "sharedPrefs"
const val ONBOARD: String = "onboard"
const val EMAIL_FROM_GOOGLE: String = "google_email"
const val SIGN_UP_WITH_GGOGLE: String = "sign_up_with_google"
const val LOG_OUT: String = "log_out"
const val LASTNAME: String = "lastname"
const val FIRSTNAME: String = "firstname"
const val PHONE: String = "phone"
const val GENDER: String = "gender"
const val DOB: String = "dob"
const val PASSWORD: String = "password"
const val ADDRESS: String = "address"
const val EMAIL: String = "email"
const val STATE: String = "state"
const val LGA: String = "lga"
const val ZIPCODE: String = "zipcode"
const val LONGITUDE: String = "longitude"
const val LATITUDE: String = "latitude"
const val TOKEN: String = "token"
const val USERID: String = "id"
const val GROUND_FORCE_IMAGE_NAME = "ground_force_profile_picture.jpg"
const val UNAUTHORIZED = 401
const val LOCATION_VERIFICATION = "location_verification"
const val COMPLETED_REGISTRATION = "registration_completed"
const val BANKCODE = "bankcode"
const val ACCOUNTNUMBER = "account_number"
const val RELIGION = "religion"
const val ADDITIONALPHONENUMBER = "additional_phone_number"
const val AVATAR_URL = "avatar_url"
const val PUBLIC_ID = "public_url"
const val IS_VERIFIED = "is_verified"
const val BANKNAME = "bankname"
const val IS_LOCATION_VERIFIED = "is_location_verified"

const val IMAGE_URL = "image_url"



